# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    
  pull_request:
    branches: [ "master" ]
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: windows-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Build
      run: dotnet publish
      
    - name: Copy files
      run: cp  ./bin/Release/net9.0/win-x64/publish/Axolotl.BDSEditor.exe ./Axolotl.BDSEditor.exe
      
    - name: Init git
      run: |
            git config --global user.email "YoumiHa@outlook.com"
            git config --global user.name "YoumiHaLH"
    - name: Set up version
      run: Set-Variable -Name VERSION -Value "${{ $(date +%Y%m%d%H%M) }}"
    - name: Create tag
      run: git tag -a $VERSION -m "Release ${{ env.VERSION }}"
    - name: Push tag
      run: git push origin ${{ env.VERSION }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ env.VERSION }}
          name: BDSEditor
          files: Axolotl.BDSEditor.exe
